// Content for About / Disclosure / Privacy / Terms, per language.
// Replace CONTACT_EMAIL with your contact address before applying for AdSense.
const CONTACT = 'CONTACT_EMAIL';

export const INFO_PAGES = {
  about: {
    en: { title: 'About Us', body: `<p>DealDesi collects the best deals from India’s top online stores — Amazon, Flipkart, Myntra, Meesho, AJIO, Nykaa, Tata CLiQ, JioMart, Croma and FirstCry — in one place, updated every day.</p><p>Our buying guides help you choose the right product for your budget.</p><p>Contact: ${CONTACT}</p>` },
    hi: { title: 'हमारे बारे में', body: `<p>DealDesi भारत के टॉप ऑनलाइन स्टोर्स — Amazon, Flipkart, Myntra, Meesho, AJIO, Nykaa, Tata CLiQ, JioMart, Croma और FirstCry — की बेस्ट डील्स एक जगह, रोज़ अपडेट करके दिखाता है।</p><p>हमारी खरीदारी गाइड आपके बजट के हिसाब से सही प्रोडक्ट चुनने में मदद करती हैं।</p><p>संपर्क: ${CONTACT}</p>` },
    hinglish: { title: 'About Us', body: `<p>DealDesi India ke top online stores — Amazon, Flipkart, Myntra, Meesho, AJIO, Nykaa, Tata CLiQ, JioMart, Croma aur FirstCry — ki best deals ek jagah, roz update karke dikhata hai.</p><p>Hamari buying guides aapke budget ke hisaab se sahi product chunne mein help karti hain.</p><p>Contact: ${CONTACT}</p>` },
  },
  disclosure: {
    en: { title: 'Affiliate Disclosure', body: `<p>Some links on this website are affiliate links. If you click one and make a purchase, we may earn a commission from the store, <strong>at no extra cost to you</strong>.</p><p>DealDesi is a participant in the Amazon Associates Programme and other affiliate programmes, including the Flipkart Affiliate Programme and affiliate networks that work with Indian stores. As an Amazon Associate we earn from qualifying purchases.</p><p>Prices, offers and availability are set by the stores and can change at any time. Always check the final price on the store’s website before buying.</p>` },
    hi: { title: 'एफ़िलिएट जानकारी', body: `<p>इस वेबसाइट के कुछ लिंक एफ़िलिएट लिंक हैं। अगर आप उन पर क्लिक करके खरीदारी करते हैं, तो हमें स्टोर से कमीशन मिल सकता है, <strong>आपको कोई अतिरिक्त खर्च नहीं</strong>।</p><p>DealDesi, Amazon Associates प्रोग्राम और अन्य एफ़िलिएट प्रोग्राम (जैसे Flipkart Affiliate) का हिस्सा है। Amazon Associate के रूप में हम योग्य खरीदारी से कमाते हैं।</p><p>कीमत, ऑफ़र और उपलब्धता स्टोर तय करते हैं और कभी भी बदल सकते हैं। खरीदने से पहले स्टोर पर अंतिम कीमत ज़रूर देखें।</p>` },
    hinglish: { title: 'Affiliate Disclosure', body: `<p>Is website ke kuch links affiliate links hain. Agar aap unpe click karke kuch kharidte ho, toh humein store se commission mil sakta hai, <strong>aapko koi extra kharcha nahi</strong>.</p><p>DealDesi, Amazon Associates programme aur doosre affiliate programmes (jaise Flipkart Affiliate) ka hissa hai. As an Amazon Associate hum qualifying purchases se kamaate hain.</p><p>Price, offers aur stock store decide karte hain aur kabhi bhi badal sakte hain. Kharidne se pehle store pe final price zaroor check karo.</p>` },
  },
  privacy: {
    en: { title: 'Privacy Policy', body: `<p>We do not ask you to create an account and we do not collect your name, phone number or payment details.</p><h2>Cookies and third parties</h2><p>When you click a store link, the store or affiliate network may set cookies to track the referral. If advertising is enabled, Google and its partners may use cookies to show ads based on your visits to this and other websites. You can manage ad personalisation at <a href="https://adssettings.google.com" rel="nofollow">Google Ads Settings</a>.</p><h2>Analytics</h2><p>We may use privacy-friendly analytics to count page views. This data is not used to identify you.</p><h2>Your rights</h2><p>Under India’s Digital Personal Data Protection Act, 2023, you may contact us about any personal data concerns: ${CONTACT}</p>` },
    hi: { title: 'प्राइवेसी पॉलिसी', body: `<p>हम आपसे अकाउंट नहीं बनवाते और आपका नाम, फ़ोन नंबर या पेमेंट जानकारी नहीं लेते।</p><h2>कुकीज़ और थर्ड पार्टी</h2><p>स्टोर लिंक पर क्लिक करने पर स्टोर या एफ़िलिएट नेटवर्क रेफ़रल ट्रैक करने के लिए कुकीज़ सेट कर सकते हैं। विज्ञापन चालू होने पर Google और उसके पार्टनर विज्ञापन दिखाने के लिए कुकीज़ इस्तेमाल कर सकते हैं। आप <a href="https://adssettings.google.com" rel="nofollow">Google Ads Settings</a> पर इसे बदल सकते हैं।</p><h2>आपके अधिकार</h2><p>डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम, 2023 के तहत किसी भी चिंता के लिए संपर्क करें: ${CONTACT}</p>` },
    hinglish: { title: 'Privacy Policy', body: `<p>Hum aapse account nahi banwate aur aapka naam, phone number ya payment details nahi lete.</p><h2>Cookies aur third parties</h2><p>Store link pe click karne par store ya affiliate network referral track karne ke liye cookies set kar sakte hain. Ads on hone par Google aur uske partners ads dikhane ke liye cookies use kar sakte hain. Aap <a href="https://adssettings.google.com" rel="nofollow">Google Ads Settings</a> pe ise manage kar sakte ho.</p><h2>Aapke rights</h2><p>Digital Personal Data Protection Act, 2023 ke under kisi bhi concern ke liye contact karo: ${CONTACT}</p>` },
  },
  terms: {
    en: { title: 'Terms of Use', body: `<p>DealDesi is an information website. We do not sell products. All purchases happen on the store’s own website and are subject to that store’s terms, prices, returns and warranty.</p><p>We try to keep information accurate but cannot guarantee that prices, discounts or stock shown here are current. Product names and trademarks belong to their owners.</p>` },
    hi: { title: 'उपयोग की शर्तें', body: `<p>DealDesi एक जानकारी देने वाली वेबसाइट है। हम प्रोडक्ट नहीं बेचते। सारी खरीदारी स्टोर की अपनी वेबसाइट पर होती है और उस स्टोर की शर्तें, कीमत, रिटर्न और वारंटी लागू होती हैं।</p><p>हम जानकारी सही रखने की कोशिश करते हैं, पर यहाँ दिखी कीमत, छूट या स्टॉक की गारंटी नहीं दे सकते। प्रोडक्ट के नाम और ट्रेडमार्क उनके मालिकों के हैं।</p>` },
    hinglish: { title: 'Terms of Use', body: `<p>DealDesi ek information website hai. Hum products nahi bechte. Saari kharidari store ki apni website pe hoti hai aur us store ke terms, price, returns aur warranty lagu hote hain.</p><p>Hum information sahi rakhne ki koshish karte hain, par yahan dikhe price, discount ya stock ki guarantee nahi de sakte. Product names aur trademarks unke owners ke hain.</p>` },
  },
};
